source 'https://cdn.cocoapods.org/'
platform :ios, '8.0'

target 'SFVehicles' do
  use_frameworks!

  pod 'GeoFire', :path => '../../'

  target 'SFVehiclesTests' do
    inherit! :search_paths
  end

end
