# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'SFVehicles' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GeoFire', :path => '../../'

  target 'SFVehiclesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
